/* Generated By:JavaCC: Do not edit this line. BCLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BCLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAR = 4;
  /** RegularExpression Id. */
  int RPAR = 5;
  /** RegularExpression Id. */
  int LBRACK = 6;
  /** RegularExpression Id. */
  int RBRACK = 7;
  /** RegularExpression Id. */
  int LSQ_BRACK = 8;
  /** RegularExpression Id. */
  int RSQ_BRACK = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int QUOT = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int SEP = 15;
  /** RegularExpression Id. */
  int NULL = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int GTE = 22;
  /** RegularExpression Id. */
  int LTE = 23;
  /** RegularExpression Id. */
  int EQUAL = 24;
  /** RegularExpression Id. */
  int DIFF = 25;
  /** RegularExpression Id. */
  int MINUS = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int MUL = 29;
  /** RegularExpression Id. */
  int MOD = 30;
  /** RegularExpression Id. */
  int POWER = 31;
  /** RegularExpression Id. */
  int PLUSPLUS = 32;
  /** RegularExpression Id. */
  int MINUSMINUS = 33;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 34;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 35;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 36;
  /** RegularExpression Id. */
  int MUL_ASSIGN = 37;
  /** RegularExpression Id. */
  int MOD_ASSIGN = 38;
  /** RegularExpression Id. */
  int POW_ASSIGN = 39;
  /** RegularExpression Id. */
  int IBASE = 40;
  /** RegularExpression Id. */
  int OBASE = 41;
  /** RegularExpression Id. */
  int SCALE = 42;
  /** RegularExpression Id. */
  int LAST = 43;
  /** RegularExpression Id. */
  int SQRT = 44;
  /** RegularExpression Id. */
  int LENGTH = 45;
  /** RegularExpression Id. */
  int FUNC_S = 46;
  /** RegularExpression Id. */
  int FUNC_C = 47;
  /** RegularExpression Id. */
  int FUNC_E = 48;
  /** RegularExpression Id. */
  int FUNC_L = 49;
  /** RegularExpression Id. */
  int FUNC_A = 50;
  /** RegularExpression Id. */
  int FUNC_J = 51;
  /** RegularExpression Id. */
  int IF = 52;
  /** RegularExpression Id. */
  int FOR = 53;
  /** RegularExpression Id. */
  int ELSE = 54;
  /** RegularExpression Id. */
  int WHILE = 55;
  /** RegularExpression Id. */
  int PRINT = 56;
  /** RegularExpression Id. */
  int DEFINE = 57;
  /** RegularExpression Id. */
  int BREAK = 58;
  /** RegularExpression Id. */
  int AUTO = 59;
  /** RegularExpression Id. */
  int QUIT = 60;
  /** RegularExpression Id. */
  int RETURN = 61;
  /** RegularExpression Id. */
  int CONTINUE = 62;
  /** RegularExpression Id. */
  int DIGIT = 63;
  /** RegularExpression Id. */
  int LETTER = 64;
  /** RegularExpression Id. */
  int SYMBOL = 65;
  /** RegularExpression Id. */
  int INTEGER = 66;
  /** RegularExpression Id. */
  int REAL = 67;
  /** RegularExpression Id. */
  int ALNUM = 68;
  /** RegularExpression Id. */
  int NUMBER = 69;
  /** RegularExpression Id. */
  int ID = 70;
  /** RegularExpression Id. */
  int STRING = 71;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"\\\"\"",
    "\".\"",
    "<SEP>",
    "<NULL>",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"-\"",
    "\"+\"",
    "\"/\"",
    "\"*\"",
    "\"%\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\"-=\"",
    "\"+=\"",
    "\"/=\"",
    "\"*=\"",
    "\"%=\"",
    "\"^=\"",
    "\"ibase\"",
    "\"obase\"",
    "\"scale\"",
    "<LAST>",
    "\"sqrt\"",
    "\"length\"",
    "\"s\"",
    "\"c\"",
    "\"e\"",
    "\"l\"",
    "\"a\"",
    "\"j\"",
    "\"if\"",
    "\"for\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"define\"",
    "\"break\"",
    "\"auto\"",
    "\"quit\"",
    "\"return\"",
    "\"continue\"",
    "<DIGIT>",
    "<LETTER>",
    "<SYMBOL>",
    "<INTEGER>",
    "<REAL>",
    "<ALNUM>",
    "<NUMBER>",
    "<ID>",
    "<STRING>",
  };

}
